name: Observability Release tests workflow in Bundled OpenSearch Dashboards
on:
  push:
    branches:
      - conjwang/parallel
jobs:
  tests:
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Observability
      test-command: yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/observability-dashboards/*'